// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartboxInterface.proto

package SmartboxInterfaceProtoV1;

public final class SmartboxInterface {
  private SmartboxInterface() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes pin = 1;
    /**
     * <code>optional bytes pin = 1;</code>
     */
    boolean hasPin();
    /**
     * <code>optional bytes pin = 1;</code>
     */
    com.google.protobuf.ByteString getPin();

    // optional bytes jdpin = 2;
    /**
     * <code>optional bytes jdpin = 2;</code>
     */
    boolean hasJdpin();
    /**
     * <code>optional bytes jdpin = 2;</code>
     */
    com.google.protobuf.ByteString getJdpin();

    // optional bytes uid = 3;
    /**
     * <code>optional bytes uid = 3;</code>
     */
    boolean hasUid();
    /**
     * <code>optional bytes uid = 3;</code>
     */
    com.google.protobuf.ByteString getUid();

    // optional bytes uuid = 4;
    /**
     * <code>optional bytes uuid = 4;</code>
     */
    boolean hasUuid();
    /**
     * <code>optional bytes uuid = 4;</code>
     */
    com.google.protobuf.ByteString getUuid();

    // optional bytes last_query = 5;
    /**
     * <code>optional bytes last_query = 5;</code>
     */
    boolean hasLastQuery();
    /**
     * <code>optional bytes last_query = 5;</code>
     */
    com.google.protobuf.ByteString getLastQuery();

    // optional bytes authtp = 6;
    /**
     * <code>optional bytes authtp = 6;</code>
     */
    boolean hasAuthtp();
    /**
     * <code>optional bytes authtp = 6;</code>
     */
    com.google.protobuf.ByteString getAuthtp();

    // optional bytes pvid = 7;
    /**
     * <code>optional bytes pvid = 7;</code>
     */
    boolean hasPvid();
    /**
     * <code>optional bytes pvid = 7;</code>
     */
    com.google.protobuf.ByteString getPvid();
  }
  /**
   * Protobuf type {@code SmartboxInterfaceProtoV1.UserInfo}
   */
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessage
      implements UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserInfo defaultInstance;
    public static UserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public UserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              pin_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              jdpin_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              uid_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              uuid_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              lastQuery_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              authtp_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              pvid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_UserInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.class, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<UserInfo> PARSER =
        new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes pin = 1;
    public static final int PIN_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString pin_;
    /**
     * <code>optional bytes pin = 1;</code>
     */
    public boolean hasPin() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes pin = 1;</code>
     */
    public com.google.protobuf.ByteString getPin() {
      return pin_;
    }

    // optional bytes jdpin = 2;
    public static final int JDPIN_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString jdpin_;
    /**
     * <code>optional bytes jdpin = 2;</code>
     */
    public boolean hasJdpin() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes jdpin = 2;</code>
     */
    public com.google.protobuf.ByteString getJdpin() {
      return jdpin_;
    }

    // optional bytes uid = 3;
    public static final int UID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString uid_;
    /**
     * <code>optional bytes uid = 3;</code>
     */
    public boolean hasUid() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes uid = 3;</code>
     */
    public com.google.protobuf.ByteString getUid() {
      return uid_;
    }

    // optional bytes uuid = 4;
    public static final int UUID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString uuid_;
    /**
     * <code>optional bytes uuid = 4;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes uuid = 4;</code>
     */
    public com.google.protobuf.ByteString getUuid() {
      return uuid_;
    }

    // optional bytes last_query = 5;
    public static final int LAST_QUERY_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString lastQuery_;
    /**
     * <code>optional bytes last_query = 5;</code>
     */
    public boolean hasLastQuery() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes last_query = 5;</code>
     */
    public com.google.protobuf.ByteString getLastQuery() {
      return lastQuery_;
    }

    // optional bytes authtp = 6;
    public static final int AUTHTP_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString authtp_;
    /**
     * <code>optional bytes authtp = 6;</code>
     */
    public boolean hasAuthtp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes authtp = 6;</code>
     */
    public com.google.protobuf.ByteString getAuthtp() {
      return authtp_;
    }

    // optional bytes pvid = 7;
    public static final int PVID_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString pvid_;
    /**
     * <code>optional bytes pvid = 7;</code>
     */
    public boolean hasPvid() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes pvid = 7;</code>
     */
    public com.google.protobuf.ByteString getPvid() {
      return pvid_;
    }

    private void initFields() {
      pin_ = com.google.protobuf.ByteString.EMPTY;
      jdpin_ = com.google.protobuf.ByteString.EMPTY;
      uid_ = com.google.protobuf.ByteString.EMPTY;
      uuid_ = com.google.protobuf.ByteString.EMPTY;
      lastQuery_ = com.google.protobuf.ByteString.EMPTY;
      authtp_ = com.google.protobuf.ByteString.EMPTY;
      pvid_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, pin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, jdpin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, uuid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, lastQuery_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, authtp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, pvid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, pin_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, jdpin_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, uid_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, uuid_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, lastQuery_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, authtp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, pvid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SmartboxInterfaceProtoV1.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_UserInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.class, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder.class);
      }

      // Construct using SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pin_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        jdpin_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        uid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        uuid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        lastQuery_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        authtp_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        pvid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_UserInfo_descriptor;
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo getDefaultInstanceForType() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance();
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo build() {
        SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo buildPartial() {
        SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo result = new SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pin_ = pin_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jdpin_ = jdpin_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.uid_ = uid_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.lastQuery_ = lastQuery_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.authtp_ = authtp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.pvid_ = pvid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo) {
          return mergeFrom((SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo other) {
        if (other == SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance()) return this;
        if (other.hasPin()) {
          setPin(other.getPin());
        }
        if (other.hasJdpin()) {
          setJdpin(other.getJdpin());
        }
        if (other.hasUid()) {
          setUid(other.getUid());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        if (other.hasLastQuery()) {
          setLastQuery(other.getLastQuery());
        }
        if (other.hasAuthtp()) {
          setAuthtp(other.getAuthtp());
        }
        if (other.hasPvid()) {
          setPvid(other.getPvid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes pin = 1;
      private com.google.protobuf.ByteString pin_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pin = 1;</code>
       */
      public boolean hasPin() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes pin = 1;</code>
       */
      public com.google.protobuf.ByteString getPin() {
        return pin_;
      }
      /**
       * <code>optional bytes pin = 1;</code>
       */
      public Builder setPin(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pin = 1;</code>
       */
      public Builder clearPin() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pin_ = getDefaultInstance().getPin();
        onChanged();
        return this;
      }

      // optional bytes jdpin = 2;
      private com.google.protobuf.ByteString jdpin_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes jdpin = 2;</code>
       */
      public boolean hasJdpin() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes jdpin = 2;</code>
       */
      public com.google.protobuf.ByteString getJdpin() {
        return jdpin_;
      }
      /**
       * <code>optional bytes jdpin = 2;</code>
       */
      public Builder setJdpin(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jdpin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes jdpin = 2;</code>
       */
      public Builder clearJdpin() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jdpin_ = getDefaultInstance().getJdpin();
        onChanged();
        return this;
      }

      // optional bytes uid = 3;
      private com.google.protobuf.ByteString uid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uid = 3;</code>
       */
      public boolean hasUid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes uid = 3;</code>
       */
      public com.google.protobuf.ByteString getUid() {
        return uid_;
      }
      /**
       * <code>optional bytes uid = 3;</code>
       */
      public Builder setUid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uid = 3;</code>
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }

      // optional bytes uuid = 4;
      private com.google.protobuf.ByteString uuid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes uuid = 4;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes uuid = 4;</code>
       */
      public com.google.protobuf.ByteString getUuid() {
        return uuid_;
      }
      /**
       * <code>optional bytes uuid = 4;</code>
       */
      public Builder setUuid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes uuid = 4;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }

      // optional bytes last_query = 5;
      private com.google.protobuf.ByteString lastQuery_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes last_query = 5;</code>
       */
      public boolean hasLastQuery() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes last_query = 5;</code>
       */
      public com.google.protobuf.ByteString getLastQuery() {
        return lastQuery_;
      }
      /**
       * <code>optional bytes last_query = 5;</code>
       */
      public Builder setLastQuery(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        lastQuery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes last_query = 5;</code>
       */
      public Builder clearLastQuery() {
        bitField0_ = (bitField0_ & ~0x00000010);
        lastQuery_ = getDefaultInstance().getLastQuery();
        onChanged();
        return this;
      }

      // optional bytes authtp = 6;
      private com.google.protobuf.ByteString authtp_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes authtp = 6;</code>
       */
      public boolean hasAuthtp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes authtp = 6;</code>
       */
      public com.google.protobuf.ByteString getAuthtp() {
        return authtp_;
      }
      /**
       * <code>optional bytes authtp = 6;</code>
       */
      public Builder setAuthtp(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        authtp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes authtp = 6;</code>
       */
      public Builder clearAuthtp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        authtp_ = getDefaultInstance().getAuthtp();
        onChanged();
        return this;
      }

      // optional bytes pvid = 7;
      private com.google.protobuf.ByteString pvid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes pvid = 7;</code>
       */
      public boolean hasPvid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes pvid = 7;</code>
       */
      public com.google.protobuf.ByteString getPvid() {
        return pvid_;
      }
      /**
       * <code>optional bytes pvid = 7;</code>
       */
      public Builder setPvid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        pvid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes pvid = 7;</code>
       */
      public Builder clearPvid() {
        bitField0_ = (bitField0_ & ~0x00000040);
        pvid_ = getDefaultInstance().getPvid();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SmartboxInterfaceProtoV1.UserInfo)
    }

    static {
      defaultInstance = new UserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SmartboxInterfaceProtoV1.UserInfo)
  }

  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bytes keyword = 1;
    /**
     * <code>required bytes keyword = 1;</code>
     */
    boolean hasKeyword();
    /**
     * <code>required bytes keyword = 1;</code>
     */
    com.google.protobuf.ByteString getKeyword();

    // required bytes terminal = 2;
    /**
     * <code>required bytes terminal = 2;</code>
     */
    boolean hasTerminal();
    /**
     * <code>required bytes terminal = 2;</code>
     */
    com.google.protobuf.ByteString getTerminal();

    // optional bytes zip = 3;
    /**
     * <code>optional bytes zip = 3;</code>
     */
    boolean hasZip();
    /**
     * <code>optional bytes zip = 3;</code>
     */
    com.google.protobuf.ByteString getZip();

    // optional bytes callback = 4;
    /**
     * <code>optional bytes callback = 4;</code>
     */
    boolean hasCallback();
    /**
     * <code>optional bytes callback = 4;</code>
     */
    com.google.protobuf.ByteString getCallback();

    // optional bytes bucket = 5;
    /**
     * <code>optional bytes bucket = 5;</code>
     */
    boolean hasBucket();
    /**
     * <code>optional bytes bucket = 5;</code>
     */
    com.google.protobuf.ByteString getBucket();

    // optional bytes timestamp = 6;
    /**
     * <code>optional bytes timestamp = 6;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>optional bytes timestamp = 6;</code>
     */
    com.google.protobuf.ByteString getTimestamp();

    // optional bytes add = 7;
    /**
     * <code>optional bytes add = 7;</code>
     */
    boolean hasAdd();
    /**
     * <code>optional bytes add = 7;</code>
     */
    com.google.protobuf.ByteString getAdd();

    // required bytes reqid = 8;
    /**
     * <code>required bytes reqid = 8;</code>
     */
    boolean hasReqid();
    /**
     * <code>required bytes reqid = 8;</code>
     */
    com.google.protobuf.ByteString getReqid();

    // optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;
    /**
     * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
     */
    boolean hasUserinfo();
    /**
     * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
     */
    SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo getUserinfo();
    /**
     * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
     */
    SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder getUserinfoOrBuilder();
  }
  /**
   * Protobuf type {@code SmartboxInterfaceProtoV1.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              keyword_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              terminal_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              zip_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              callback_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              bucket_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              add_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              reqid_ = input.readBytes();
              break;
            }
            case 74: {
              SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000100) == 0x00000100)) {
                subBuilder = userinfo_.toBuilder();
              }
              userinfo_ = input.readMessage(SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userinfo_);
                userinfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000100;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Request_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SmartboxInterfaceProtoV1.SmartboxInterface.Request.class, SmartboxInterfaceProtoV1.SmartboxInterface.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bytes keyword = 1;
    public static final int KEYWORD_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString keyword_;
    /**
     * <code>required bytes keyword = 1;</code>
     */
    public boolean hasKeyword() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes keyword = 1;</code>
     */
    public com.google.protobuf.ByteString getKeyword() {
      return keyword_;
    }

    // required bytes terminal = 2;
    public static final int TERMINAL_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString terminal_;
    /**
     * <code>required bytes terminal = 2;</code>
     */
    public boolean hasTerminal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes terminal = 2;</code>
     */
    public com.google.protobuf.ByteString getTerminal() {
      return terminal_;
    }

    // optional bytes zip = 3;
    public static final int ZIP_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString zip_;
    /**
     * <code>optional bytes zip = 3;</code>
     */
    public boolean hasZip() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes zip = 3;</code>
     */
    public com.google.protobuf.ByteString getZip() {
      return zip_;
    }

    // optional bytes callback = 4;
    public static final int CALLBACK_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString callback_;
    /**
     * <code>optional bytes callback = 4;</code>
     */
    public boolean hasCallback() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes callback = 4;</code>
     */
    public com.google.protobuf.ByteString getCallback() {
      return callback_;
    }

    // optional bytes bucket = 5;
    public static final int BUCKET_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString bucket_;
    /**
     * <code>optional bytes bucket = 5;</code>
     */
    public boolean hasBucket() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes bucket = 5;</code>
     */
    public com.google.protobuf.ByteString getBucket() {
      return bucket_;
    }

    // optional bytes timestamp = 6;
    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString timestamp_;
    /**
     * <code>optional bytes timestamp = 6;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes timestamp = 6;</code>
     */
    public com.google.protobuf.ByteString getTimestamp() {
      return timestamp_;
    }

    // optional bytes add = 7;
    public static final int ADD_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString add_;
    /**
     * <code>optional bytes add = 7;</code>
     */
    public boolean hasAdd() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes add = 7;</code>
     */
    public com.google.protobuf.ByteString getAdd() {
      return add_;
    }

    // required bytes reqid = 8;
    public static final int REQID_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString reqid_;
    /**
     * <code>required bytes reqid = 8;</code>
     */
    public boolean hasReqid() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required bytes reqid = 8;</code>
     */
    public com.google.protobuf.ByteString getReqid() {
      return reqid_;
    }

    // optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;
    public static final int USERINFO_FIELD_NUMBER = 9;
    private SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo userinfo_;
    /**
     * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
     */
    public boolean hasUserinfo() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
     */
    public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo getUserinfo() {
      return userinfo_;
    }
    /**
     * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
     */
    public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder getUserinfoOrBuilder() {
      return userinfo_;
    }

    private void initFields() {
      keyword_ = com.google.protobuf.ByteString.EMPTY;
      terminal_ = com.google.protobuf.ByteString.EMPTY;
      zip_ = com.google.protobuf.ByteString.EMPTY;
      callback_ = com.google.protobuf.ByteString.EMPTY;
      bucket_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = com.google.protobuf.ByteString.EMPTY;
      add_ = com.google.protobuf.ByteString.EMPTY;
      reqid_ = com.google.protobuf.ByteString.EMPTY;
      userinfo_ = SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKeyword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTerminal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasReqid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, keyword_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, terminal_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, zip_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, callback_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, bucket_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, timestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, add_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, reqid_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, userinfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, keyword_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, terminal_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, zip_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, callback_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, bucket_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, timestamp_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, add_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, reqid_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, userinfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SmartboxInterfaceProtoV1.SmartboxInterface.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SmartboxInterfaceProtoV1.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SmartboxInterfaceProtoV1.SmartboxInterface.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Request_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SmartboxInterfaceProtoV1.SmartboxInterface.Request.class, SmartboxInterfaceProtoV1.SmartboxInterface.Request.Builder.class);
      }

      // Construct using SmartboxInterfaceProtoV1.SmartboxInterface.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserinfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        keyword_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        terminal_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        zip_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        callback_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        bucket_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        add_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        reqid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (userinfoBuilder_ == null) {
          userinfo_ = SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance();
        } else {
          userinfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Request_descriptor;
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.Request getDefaultInstanceForType() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.Request.getDefaultInstance();
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.Request build() {
        SmartboxInterfaceProtoV1.SmartboxInterface.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.Request buildPartial() {
        SmartboxInterfaceProtoV1.SmartboxInterface.Request result = new SmartboxInterfaceProtoV1.SmartboxInterface.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.keyword_ = keyword_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.terminal_ = terminal_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.zip_ = zip_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.callback_ = callback_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.bucket_ = bucket_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.add_ = add_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.reqid_ = reqid_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (userinfoBuilder_ == null) {
          result.userinfo_ = userinfo_;
        } else {
          result.userinfo_ = userinfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SmartboxInterfaceProtoV1.SmartboxInterface.Request) {
          return mergeFrom((SmartboxInterfaceProtoV1.SmartboxInterface.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SmartboxInterfaceProtoV1.SmartboxInterface.Request other) {
        if (other == SmartboxInterfaceProtoV1.SmartboxInterface.Request.getDefaultInstance()) return this;
        if (other.hasKeyword()) {
          setKeyword(other.getKeyword());
        }
        if (other.hasTerminal()) {
          setTerminal(other.getTerminal());
        }
        if (other.hasZip()) {
          setZip(other.getZip());
        }
        if (other.hasCallback()) {
          setCallback(other.getCallback());
        }
        if (other.hasBucket()) {
          setBucket(other.getBucket());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasAdd()) {
          setAdd(other.getAdd());
        }
        if (other.hasReqid()) {
          setReqid(other.getReqid());
        }
        if (other.hasUserinfo()) {
          mergeUserinfo(other.getUserinfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKeyword()) {
          
          return false;
        }
        if (!hasTerminal()) {
          
          return false;
        }
        if (!hasReqid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SmartboxInterfaceProtoV1.SmartboxInterface.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SmartboxInterfaceProtoV1.SmartboxInterface.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bytes keyword = 1;
      private com.google.protobuf.ByteString keyword_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes keyword = 1;</code>
       */
      public boolean hasKeyword() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes keyword = 1;</code>
       */
      public com.google.protobuf.ByteString getKeyword() {
        return keyword_;
      }
      /**
       * <code>required bytes keyword = 1;</code>
       */
      public Builder setKeyword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes keyword = 1;</code>
       */
      public Builder clearKeyword() {
        bitField0_ = (bitField0_ & ~0x00000001);
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }

      // required bytes terminal = 2;
      private com.google.protobuf.ByteString terminal_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes terminal = 2;</code>
       */
      public boolean hasTerminal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes terminal = 2;</code>
       */
      public com.google.protobuf.ByteString getTerminal() {
        return terminal_;
      }
      /**
       * <code>required bytes terminal = 2;</code>
       */
      public Builder setTerminal(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        terminal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes terminal = 2;</code>
       */
      public Builder clearTerminal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        terminal_ = getDefaultInstance().getTerminal();
        onChanged();
        return this;
      }

      // optional bytes zip = 3;
      private com.google.protobuf.ByteString zip_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes zip = 3;</code>
       */
      public boolean hasZip() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes zip = 3;</code>
       */
      public com.google.protobuf.ByteString getZip() {
        return zip_;
      }
      /**
       * <code>optional bytes zip = 3;</code>
       */
      public Builder setZip(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        zip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes zip = 3;</code>
       */
      public Builder clearZip() {
        bitField0_ = (bitField0_ & ~0x00000004);
        zip_ = getDefaultInstance().getZip();
        onChanged();
        return this;
      }

      // optional bytes callback = 4;
      private com.google.protobuf.ByteString callback_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes callback = 4;</code>
       */
      public boolean hasCallback() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes callback = 4;</code>
       */
      public com.google.protobuf.ByteString getCallback() {
        return callback_;
      }
      /**
       * <code>optional bytes callback = 4;</code>
       */
      public Builder setCallback(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        callback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes callback = 4;</code>
       */
      public Builder clearCallback() {
        bitField0_ = (bitField0_ & ~0x00000008);
        callback_ = getDefaultInstance().getCallback();
        onChanged();
        return this;
      }

      // optional bytes bucket = 5;
      private com.google.protobuf.ByteString bucket_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes bucket = 5;</code>
       */
      public boolean hasBucket() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes bucket = 5;</code>
       */
      public com.google.protobuf.ByteString getBucket() {
        return bucket_;
      }
      /**
       * <code>optional bytes bucket = 5;</code>
       */
      public Builder setBucket(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bucket_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes bucket = 5;</code>
       */
      public Builder clearBucket() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bucket_ = getDefaultInstance().getBucket();
        onChanged();
        return this;
      }

      // optional bytes timestamp = 6;
      private com.google.protobuf.ByteString timestamp_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes timestamp = 6;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes timestamp = 6;</code>
       */
      public com.google.protobuf.ByteString getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional bytes timestamp = 6;</code>
       */
      public Builder setTimestamp(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }

      // optional bytes add = 7;
      private com.google.protobuf.ByteString add_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes add = 7;</code>
       */
      public boolean hasAdd() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes add = 7;</code>
       */
      public com.google.protobuf.ByteString getAdd() {
        return add_;
      }
      /**
       * <code>optional bytes add = 7;</code>
       */
      public Builder setAdd(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        add_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes add = 7;</code>
       */
      public Builder clearAdd() {
        bitField0_ = (bitField0_ & ~0x00000040);
        add_ = getDefaultInstance().getAdd();
        onChanged();
        return this;
      }

      // required bytes reqid = 8;
      private com.google.protobuf.ByteString reqid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes reqid = 8;</code>
       */
      public boolean hasReqid() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required bytes reqid = 8;</code>
       */
      public com.google.protobuf.ByteString getReqid() {
        return reqid_;
      }
      /**
       * <code>required bytes reqid = 8;</code>
       */
      public Builder setReqid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        reqid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes reqid = 8;</code>
       */
      public Builder clearReqid() {
        bitField0_ = (bitField0_ & ~0x00000080);
        reqid_ = getDefaultInstance().getReqid();
        onChanged();
        return this;
      }

      // optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;
      private SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo userinfo_ = SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder> userinfoBuilder_;
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public boolean hasUserinfo() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo getUserinfo() {
        if (userinfoBuilder_ == null) {
          return userinfo_;
        } else {
          return userinfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public Builder setUserinfo(SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo value) {
        if (userinfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userinfo_ = value;
          onChanged();
        } else {
          userinfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public Builder setUserinfo(
          SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder builderForValue) {
        if (userinfoBuilder_ == null) {
          userinfo_ = builderForValue.build();
          onChanged();
        } else {
          userinfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public Builder mergeUserinfo(SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo value) {
        if (userinfoBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              userinfo_ != SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance()) {
            userinfo_ =
              SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.newBuilder(userinfo_).mergeFrom(value).buildPartial();
          } else {
            userinfo_ = value;
          }
          onChanged();
        } else {
          userinfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public Builder clearUserinfo() {
        if (userinfoBuilder_ == null) {
          userinfo_ = SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.getDefaultInstance();
          onChanged();
        } else {
          userinfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder getUserinfoBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getUserinfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      public SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder getUserinfoOrBuilder() {
        if (userinfoBuilder_ != null) {
          return userinfoBuilder_.getMessageOrBuilder();
        } else {
          return userinfo_;
        }
      }
      /**
       * <code>optional .SmartboxInterfaceProtoV1.UserInfo userinfo = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder> 
          getUserinfoFieldBuilder() {
        if (userinfoBuilder_ == null) {
          userinfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfo.Builder, SmartboxInterfaceProtoV1.SmartboxInterface.UserInfoOrBuilder>(
                  userinfo_,
                  getParentForChildren(),
                  isClean());
          userinfo_ = null;
        }
        return userinfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SmartboxInterfaceProtoV1.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SmartboxInterfaceProtoV1.Request)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional bytes resp = 1;
    /**
     * <code>optional bytes resp = 1;</code>
     */
    boolean hasResp();
    /**
     * <code>optional bytes resp = 1;</code>
     */
    com.google.protobuf.ByteString getResp();

    // required bytes reqid = 2;
    /**
     * <code>required bytes reqid = 2;</code>
     */
    boolean hasReqid();
    /**
     * <code>required bytes reqid = 2;</code>
     */
    com.google.protobuf.ByteString getReqid();
  }
  /**
   * Protobuf type {@code SmartboxInterfaceProtoV1.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              resp_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              reqid_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Response_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SmartboxInterfaceProtoV1.SmartboxInterface.Response.class, SmartboxInterfaceProtoV1.SmartboxInterface.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional bytes resp = 1;
    public static final int RESP_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString resp_;
    /**
     * <code>optional bytes resp = 1;</code>
     */
    public boolean hasResp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bytes resp = 1;</code>
     */
    public com.google.protobuf.ByteString getResp() {
      return resp_;
    }

    // required bytes reqid = 2;
    public static final int REQID_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString reqid_;
    /**
     * <code>required bytes reqid = 2;</code>
     */
    public boolean hasReqid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes reqid = 2;</code>
     */
    public com.google.protobuf.ByteString getReqid() {
      return reqid_;
    }

    private void initFields() {
      resp_ = com.google.protobuf.ByteString.EMPTY;
      reqid_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReqid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, resp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, reqid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, resp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, reqid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SmartboxInterfaceProtoV1.SmartboxInterface.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SmartboxInterfaceProtoV1.SmartboxInterface.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SmartboxInterfaceProtoV1.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SmartboxInterfaceProtoV1.SmartboxInterface.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Response_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SmartboxInterfaceProtoV1.SmartboxInterface.Response.class, SmartboxInterfaceProtoV1.SmartboxInterface.Response.Builder.class);
      }

      // Construct using SmartboxInterfaceProtoV1.SmartboxInterface.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        resp_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        reqid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.internal_static_SmartboxInterfaceProtoV1_Response_descriptor;
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.Response getDefaultInstanceForType() {
        return SmartboxInterfaceProtoV1.SmartboxInterface.Response.getDefaultInstance();
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.Response build() {
        SmartboxInterfaceProtoV1.SmartboxInterface.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SmartboxInterfaceProtoV1.SmartboxInterface.Response buildPartial() {
        SmartboxInterfaceProtoV1.SmartboxInterface.Response result = new SmartboxInterfaceProtoV1.SmartboxInterface.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resp_ = resp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.reqid_ = reqid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SmartboxInterfaceProtoV1.SmartboxInterface.Response) {
          return mergeFrom((SmartboxInterfaceProtoV1.SmartboxInterface.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SmartboxInterfaceProtoV1.SmartboxInterface.Response other) {
        if (other == SmartboxInterfaceProtoV1.SmartboxInterface.Response.getDefaultInstance()) return this;
        if (other.hasResp()) {
          setResp(other.getResp());
        }
        if (other.hasReqid()) {
          setReqid(other.getReqid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReqid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SmartboxInterfaceProtoV1.SmartboxInterface.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SmartboxInterfaceProtoV1.SmartboxInterface.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional bytes resp = 1;
      private com.google.protobuf.ByteString resp_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes resp = 1;</code>
       */
      public boolean hasResp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bytes resp = 1;</code>
       */
      public com.google.protobuf.ByteString getResp() {
        return resp_;
      }
      /**
       * <code>optional bytes resp = 1;</code>
       */
      public Builder setResp(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        resp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes resp = 1;</code>
       */
      public Builder clearResp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resp_ = getDefaultInstance().getResp();
        onChanged();
        return this;
      }

      // required bytes reqid = 2;
      private com.google.protobuf.ByteString reqid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes reqid = 2;</code>
       */
      public boolean hasReqid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes reqid = 2;</code>
       */
      public com.google.protobuf.ByteString getReqid() {
        return reqid_;
      }
      /**
       * <code>required bytes reqid = 2;</code>
       */
      public Builder setReqid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        reqid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes reqid = 2;</code>
       */
      public Builder clearReqid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        reqid_ = getDefaultInstance().getReqid();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SmartboxInterfaceProtoV1.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SmartboxInterfaceProtoV1.Response)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartboxInterfaceProtoV1_UserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SmartboxInterfaceProtoV1_UserInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartboxInterfaceProtoV1_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SmartboxInterfaceProtoV1_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartboxInterfaceProtoV1_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SmartboxInterfaceProtoV1_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\027SmartboxInterface.proto\022\030SmartboxInter" +
      "faceProtoV1\"s\n\010UserInfo\022\013\n\003pin\030\001 \001(\014\022\r\n\005" +
      "jdpin\030\002 \001(\014\022\013\n\003uid\030\003 \001(\014\022\014\n\004uuid\030\004 \001(\014\022\022" +
      "\n\nlast_query\030\005 \001(\014\022\016\n\006authtp\030\006 \001(\014\022\014\n\004pv" +
      "id\030\007 \001(\014\"\300\001\n\007Request\022\017\n\007keyword\030\001 \002(\014\022\020\n" +
      "\010terminal\030\002 \002(\014\022\013\n\003zip\030\003 \001(\014\022\020\n\010callback" +
      "\030\004 \001(\014\022\016\n\006bucket\030\005 \001(\014\022\021\n\ttimestamp\030\006 \001(" +
      "\014\022\013\n\003add\030\007 \001(\014\022\r\n\005reqid\030\010 \002(\014\0224\n\010userinf" +
      "o\030\t \001(\0132\".SmartboxInterfaceProtoV1.UserI" +
      "nfo\"\'\n\010Response\022\014\n\004resp\030\001 \001(\014\022\r\n\005reqid\030\002",
      " \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SmartboxInterfaceProtoV1_UserInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SmartboxInterfaceProtoV1_UserInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SmartboxInterfaceProtoV1_UserInfo_descriptor,
              new String[] { "Pin", "Jdpin", "Uid", "Uuid", "LastQuery", "Authtp", "Pvid", });
          internal_static_SmartboxInterfaceProtoV1_Request_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_SmartboxInterfaceProtoV1_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SmartboxInterfaceProtoV1_Request_descriptor,
              new String[] { "Keyword", "Terminal", "Zip", "Callback", "Bucket", "Timestamp", "Add", "Reqid", "Userinfo", });
          internal_static_SmartboxInterfaceProtoV1_Response_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_SmartboxInterfaceProtoV1_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SmartboxInterfaceProtoV1_Response_descriptor,
              new String[] { "Resp", "Reqid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
