// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package sopr.common;

public final class Protocol {
  private Protocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required uint32 roleid = 1;
    /**
     * <code>required uint32 roleid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    boolean hasRoleid();
    /**
     * <code>required uint32 roleid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    int getRoleid();

    // required uint32 channel = 2;
    /**
     * <code>required uint32 channel = 2;</code>
     *
     * <pre>
     *场景
     * </pre>
     */
    boolean hasChannel();
    /**
     * <code>required uint32 channel = 2;</code>
     *
     * <pre>
     *场景
     * </pre>
     */
    int getChannel();

    // required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];
    /**
     * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
     *
     * <pre>
     *字符集
     * </pre>
     */
    boolean hasCharset();
    /**
     * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
     *
     * <pre>
     *字符集
     * </pre>
     */
    OPRequest.Charset getCharset();

    // optional bytes keyword = 4;
    /**
     * <code>optional bytes keyword = 4;</code>
     *
     * <pre>
     *请求关键词
     * </pre>
     */
    boolean hasKeyword();
    /**
     * <code>optional bytes keyword = 4;</code>
     *
     * <pre>
     *请求关键词
     * </pre>
     */
    com.google.protobuf.ByteString getKeyword();

    // optional uint64 classid1 = 5 [default = 0];
    /**
     * <code>optional uint64 classid1 = 5 [default = 0];</code>
     *
     * <pre>
     *一级类目
     * </pre>
     */
    boolean hasClassid1();
    /**
     * <code>optional uint64 classid1 = 5 [default = 0];</code>
     *
     * <pre>
     *一级类目
     * </pre>
     */
    long getClassid1();

    // optional uint64 classid2 = 6 [default = 0];
    /**
     * <code>optional uint64 classid2 = 6 [default = 0];</code>
     *
     * <pre>
     *二级类目
     * </pre>
     */
    boolean hasClassid2();
    /**
     * <code>optional uint64 classid2 = 6 [default = 0];</code>
     *
     * <pre>
     *二级类目
     * </pre>
     */
    long getClassid2();

    // optional uint64 classid3 = 7 [default = 0];
    /**
     * <code>optional uint64 classid3 = 7 [default = 0];</code>
     *
     * <pre>
     *三级类目
     * </pre>
     */
    boolean hasClassid3();
    /**
     * <code>optional uint64 classid3 = 7 [default = 0];</code>
     *
     * <pre>
     *三级类目
     * </pre>
     */
    long getClassid3();
  }
  /**
   * Protobuf type {@code sopr.common.OPRequest}
   *
   * <pre>
   *请求结构
   * </pre>
   */
  public static final class OPRequest extends
      com.google.protobuf.GeneratedMessage
      implements OPRequestOrBuilder {
    // Use OPRequest.newBuilder() to construct.
    private OPRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPRequest defaultInstance;
    public static OPRequest getDefaultInstance() {
      return defaultInstance;
    }

    public OPRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roleid_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channel_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              Charset value = Charset.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                charset_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              keyword_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              classid1_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              classid2_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              classid3_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.internal_static_sopr_common_OPRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.internal_static_sopr_common_OPRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OPRequest.class, Builder.class);
    }

    public static com.google.protobuf.Parser<OPRequest> PARSER =
        new com.google.protobuf.AbstractParser<OPRequest>() {
      public OPRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPRequest(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OPRequest> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code sopr.common.OPRequest.Channel}
     *
     * <pre>
     *场景定义
     * </pre>
     */
    public enum Channel
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MOBILEQQ = 1;</code>
       */
      MOBILEQQ(0, 1),
      /**
       * <code>WECHAT = 2;</code>
       */
      WECHAT(1, 2),
      /**
       * <code>APP = 4;</code>
       */
      APP(2, 4),
      /**
       * <code>WEB = 8;</code>
       */
      WEB(3, 8),
      /**
       * <code>H5 = 16;</code>
       */
      H5(4, 16),
      ;

      /**
       * <code>MOBILEQQ = 1;</code>
       */
      public static final int MOBILEQQ_VALUE = 1;
      /**
       * <code>WECHAT = 2;</code>
       */
      public static final int WECHAT_VALUE = 2;
      /**
       * <code>APP = 4;</code>
       */
      public static final int APP_VALUE = 4;
      /**
       * <code>WEB = 8;</code>
       */
      public static final int WEB_VALUE = 8;
      /**
       * <code>H5 = 16;</code>
       */
      public static final int H5_VALUE = 16;


      public final int getNumber() { return value; }

      public static Channel valueOf(int value) {
        switch (value) {
          case 1: return MOBILEQQ;
          case 2: return WECHAT;
          case 4: return APP;
          case 8: return WEB;
          case 16: return H5;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Channel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Channel>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Channel>() {
              public Channel findValueByNumber(int number) {
                return Channel.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return OPRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Channel[] VALUES = values();

      public static Channel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Channel(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sopr.common.OPRequest.Channel)
    }

    /**
     * Protobuf enum {@code sopr.common.OPRequest.Charset}
     *
     * <pre>
     *字符集
     * </pre>
     */
    public enum Charset
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GBK = 1;</code>
       */
      GBK(0, 1),
      /**
       * <code>UTF8 = 2;</code>
       */
      UTF8(1, 2),
      ;

      /**
       * <code>GBK = 1;</code>
       */
      public static final int GBK_VALUE = 1;
      /**
       * <code>UTF8 = 2;</code>
       */
      public static final int UTF8_VALUE = 2;


      public final int getNumber() { return value; }

      public static Charset valueOf(int value) {
        switch (value) {
          case 1: return GBK;
          case 2: return UTF8;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Charset>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Charset>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Charset>() {
              public Charset findValueByNumber(int number) {
                return Charset.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return OPRequest.getDescriptor().getEnumTypes().get(1);
      }

      private static final Charset[] VALUES = values();

      public static Charset valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Charset(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:sopr.common.OPRequest.Charset)
    }

    private int bitField0_;
    // required uint32 roleid = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private int roleid_;
    /**
     * <code>required uint32 roleid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    public boolean hasRoleid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 roleid = 1;</code>
     *
     * <pre>
     *角色id
     * </pre>
     */
    public int getRoleid() {
      return roleid_;
    }

    // required uint32 channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    /**
     * <code>required uint32 channel = 2;</code>
     *
     * <pre>
     *场景
     * </pre>
     */
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 channel = 2;</code>
     *
     * <pre>
     *场景
     * </pre>
     */
    public int getChannel() {
      return channel_;
    }

    // required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];
    public static final int CHARSET_FIELD_NUMBER = 3;
    private Charset charset_;
    /**
     * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
     *
     * <pre>
     *字符集
     * </pre>
     */
    public boolean hasCharset() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
     *
     * <pre>
     *字符集
     * </pre>
     */
    public Charset getCharset() {
      return charset_;
    }

    // optional bytes keyword = 4;
    public static final int KEYWORD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString keyword_;
    /**
     * <code>optional bytes keyword = 4;</code>
     *
     * <pre>
     *请求关键词
     * </pre>
     */
    public boolean hasKeyword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes keyword = 4;</code>
     *
     * <pre>
     *请求关键词
     * </pre>
     */
    public com.google.protobuf.ByteString getKeyword() {
      return keyword_;
    }

    // optional uint64 classid1 = 5 [default = 0];
    public static final int CLASSID1_FIELD_NUMBER = 5;
    private long classid1_;
    /**
     * <code>optional uint64 classid1 = 5 [default = 0];</code>
     *
     * <pre>
     *一级类目
     * </pre>
     */
    public boolean hasClassid1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 classid1 = 5 [default = 0];</code>
     *
     * <pre>
     *一级类目
     * </pre>
     */
    public long getClassid1() {
      return classid1_;
    }

    // optional uint64 classid2 = 6 [default = 0];
    public static final int CLASSID2_FIELD_NUMBER = 6;
    private long classid2_;
    /**
     * <code>optional uint64 classid2 = 6 [default = 0];</code>
     *
     * <pre>
     *二级类目
     * </pre>
     */
    public boolean hasClassid2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 classid2 = 6 [default = 0];</code>
     *
     * <pre>
     *二级类目
     * </pre>
     */
    public long getClassid2() {
      return classid2_;
    }

    // optional uint64 classid3 = 7 [default = 0];
    public static final int CLASSID3_FIELD_NUMBER = 7;
    private long classid3_;
    /**
     * <code>optional uint64 classid3 = 7 [default = 0];</code>
     *
     * <pre>
     *三级类目
     * </pre>
     */
    public boolean hasClassid3() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 classid3 = 7 [default = 0];</code>
     *
     * <pre>
     *三级类目
     * </pre>
     */
    public long getClassid3() {
      return classid3_;
    }

    private void initFields() {
      roleid_ = 0;
      channel_ = 0;
      charset_ = Charset.GBK;
      keyword_ = com.google.protobuf.ByteString.EMPTY;
      classid1_ = 0L;
      classid2_ = 0L;
      classid3_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoleid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCharset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, roleid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, channel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, charset_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, keyword_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, classid1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, classid2_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, classid3_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, roleid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, channel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, charset_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, keyword_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, classid1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, classid2_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, classid3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static OPRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OPRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OPRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OPRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OPRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OPRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static OPRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static OPRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static OPRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OPRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(OPRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sopr.common.OPRequest}
     *
     * <pre>
     *请求结构
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OPRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.internal_static_sopr_common_OPRequest_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.internal_static_sopr_common_OPRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OPRequest.class, Builder.class);
      }

      // Construct using sopr.common.Protocol.OPRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roleid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        charset_ = Charset.GBK;
        bitField0_ = (bitField0_ & ~0x00000004);
        keyword_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        classid1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        classid2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        classid3_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.internal_static_sopr_common_OPRequest_descriptor;
      }

      public OPRequest getDefaultInstanceForType() {
        return OPRequest.getDefaultInstance();
      }

      public OPRequest build() {
        OPRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OPRequest buildPartial() {
        OPRequest result = new OPRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleid_ = roleid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.charset_ = charset_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.keyword_ = keyword_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.classid1_ = classid1_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.classid2_ = classid2_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.classid3_ = classid3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OPRequest) {
          return mergeFrom((OPRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OPRequest other) {
        if (other == OPRequest.getDefaultInstance()) return this;
        if (other.hasRoleid()) {
          setRoleid(other.getRoleid());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasCharset()) {
          setCharset(other.getCharset());
        }
        if (other.hasKeyword()) {
          setKeyword(other.getKeyword());
        }
        if (other.hasClassid1()) {
          setClassid1(other.getClassid1());
        }
        if (other.hasClassid2()) {
          setClassid2(other.getClassid2());
        }
        if (other.hasClassid3()) {
          setClassid3(other.getClassid3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoleid()) {
          
          return false;
        }
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasCharset()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OPRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OPRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required uint32 roleid = 1;
      private int roleid_ ;
      /**
       * <code>required uint32 roleid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public boolean hasRoleid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 roleid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public int getRoleid() {
        return roleid_;
      }
      /**
       * <code>required uint32 roleid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public Builder setRoleid(int value) {
        bitField0_ |= 0x00000001;
        roleid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 roleid = 1;</code>
       *
       * <pre>
       *角色id
       * </pre>
       */
      public Builder clearRoleid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleid_ = 0;
        onChanged();
        return this;
      }

      // required uint32 channel = 2;
      private int channel_ ;
      /**
       * <code>required uint32 channel = 2;</code>
       *
       * <pre>
       *场景
       * </pre>
       */
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 channel = 2;</code>
       *
       * <pre>
       *场景
       * </pre>
       */
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>required uint32 channel = 2;</code>
       *
       * <pre>
       *场景
       * </pre>
       */
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 channel = 2;</code>
       *
       * <pre>
       *场景
       * </pre>
       */
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        onChanged();
        return this;
      }

      // required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];
      private Charset charset_ = Charset.GBK;
      /**
       * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
       *
       * <pre>
       *字符集
       * </pre>
       */
      public boolean hasCharset() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
       *
       * <pre>
       *字符集
       * </pre>
       */
      public Charset getCharset() {
        return charset_;
      }
      /**
       * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
       *
       * <pre>
       *字符集
       * </pre>
       */
      public Builder setCharset(Charset value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        charset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];</code>
       *
       * <pre>
       *字符集
       * </pre>
       */
      public Builder clearCharset() {
        bitField0_ = (bitField0_ & ~0x00000004);
        charset_ = Charset.GBK;
        onChanged();
        return this;
      }

      // optional bytes keyword = 4;
      private com.google.protobuf.ByteString keyword_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes keyword = 4;</code>
       *
       * <pre>
       *请求关键词
       * </pre>
       */
      public boolean hasKeyword() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes keyword = 4;</code>
       *
       * <pre>
       *请求关键词
       * </pre>
       */
      public com.google.protobuf.ByteString getKeyword() {
        return keyword_;
      }
      /**
       * <code>optional bytes keyword = 4;</code>
       *
       * <pre>
       *请求关键词
       * </pre>
       */
      public Builder setKeyword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        keyword_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes keyword = 4;</code>
       *
       * <pre>
       *请求关键词
       * </pre>
       */
      public Builder clearKeyword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }

      // optional uint64 classid1 = 5 [default = 0];
      private long classid1_ ;
      /**
       * <code>optional uint64 classid1 = 5 [default = 0];</code>
       *
       * <pre>
       *一级类目
       * </pre>
       */
      public boolean hasClassid1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 classid1 = 5 [default = 0];</code>
       *
       * <pre>
       *一级类目
       * </pre>
       */
      public long getClassid1() {
        return classid1_;
      }
      /**
       * <code>optional uint64 classid1 = 5 [default = 0];</code>
       *
       * <pre>
       *一级类目
       * </pre>
       */
      public Builder setClassid1(long value) {
        bitField0_ |= 0x00000010;
        classid1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 classid1 = 5 [default = 0];</code>
       *
       * <pre>
       *一级类目
       * </pre>
       */
      public Builder clearClassid1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        classid1_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 classid2 = 6 [default = 0];
      private long classid2_ ;
      /**
       * <code>optional uint64 classid2 = 6 [default = 0];</code>
       *
       * <pre>
       *二级类目
       * </pre>
       */
      public boolean hasClassid2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 classid2 = 6 [default = 0];</code>
       *
       * <pre>
       *二级类目
       * </pre>
       */
      public long getClassid2() {
        return classid2_;
      }
      /**
       * <code>optional uint64 classid2 = 6 [default = 0];</code>
       *
       * <pre>
       *二级类目
       * </pre>
       */
      public Builder setClassid2(long value) {
        bitField0_ |= 0x00000020;
        classid2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 classid2 = 6 [default = 0];</code>
       *
       * <pre>
       *二级类目
       * </pre>
       */
      public Builder clearClassid2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        classid2_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 classid3 = 7 [default = 0];
      private long classid3_ ;
      /**
       * <code>optional uint64 classid3 = 7 [default = 0];</code>
       *
       * <pre>
       *三级类目
       * </pre>
       */
      public boolean hasClassid3() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 classid3 = 7 [default = 0];</code>
       *
       * <pre>
       *三级类目
       * </pre>
       */
      public long getClassid3() {
        return classid3_;
      }
      /**
       * <code>optional uint64 classid3 = 7 [default = 0];</code>
       *
       * <pre>
       *三级类目
       * </pre>
       */
      public Builder setClassid3(long value) {
        bitField0_ |= 0x00000040;
        classid3_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 classid3 = 7 [default = 0];</code>
       *
       * <pre>
       *三级类目
       * </pre>
       */
      public Builder clearClassid3() {
        bitField0_ = (bitField0_ & ~0x00000040);
        classid3_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sopr.common.OPRequest)
    }

    static {
      defaultInstance = new OPRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sopr.common.OPRequest)
  }

  public interface OPRequestMultiOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .sopr.common.OPRequest reqList = 1;
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    java.util.List<OPRequest>
        getReqListList();
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    OPRequest getReqList(int index);
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    int getReqListCount();
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    java.util.List<? extends OPRequestOrBuilder>
        getReqListOrBuilderList();
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    OPRequestOrBuilder getReqListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code sopr.common.OPRequestMulti}
   *
   * <pre>
   *批量请求结构-暂不支持
   * </pre>
   */
  public static final class OPRequestMulti extends
      com.google.protobuf.GeneratedMessage
      implements OPRequestMultiOrBuilder {
    // Use OPRequestMulti.newBuilder() to construct.
    private OPRequestMulti(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPRequestMulti(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPRequestMulti defaultInstance;
    public static OPRequestMulti getDefaultInstance() {
      return defaultInstance;
    }

    public OPRequestMulti getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPRequestMulti(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                reqList_ = new java.util.ArrayList<OPRequest>();
                mutable_bitField0_ |= 0x00000001;
              }
              reqList_.add(input.readMessage(OPRequest.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          reqList_ = java.util.Collections.unmodifiableList(reqList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.internal_static_sopr_common_OPRequestMulti_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.internal_static_sopr_common_OPRequestMulti_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OPRequestMulti.class, Builder.class);
    }

    public static com.google.protobuf.Parser<OPRequestMulti> PARSER =
        new com.google.protobuf.AbstractParser<OPRequestMulti>() {
      public OPRequestMulti parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPRequestMulti(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OPRequestMulti> getParserForType() {
      return PARSER;
    }

    // repeated .sopr.common.OPRequest reqList = 1;
    public static final int REQLIST_FIELD_NUMBER = 1;
    private java.util.List<OPRequest> reqList_;
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    public java.util.List<OPRequest> getReqListList() {
      return reqList_;
    }
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    public java.util.List<? extends OPRequestOrBuilder>
        getReqListOrBuilderList() {
      return reqList_;
    }
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    public int getReqListCount() {
      return reqList_.size();
    }
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    public OPRequest getReqList(int index) {
      return reqList_.get(index);
    }
    /**
     * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
     */
    public OPRequestOrBuilder getReqListOrBuilder(
        int index) {
      return reqList_.get(index);
    }

    private void initFields() {
      reqList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getReqListCount(); i++) {
        if (!getReqList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < reqList_.size(); i++) {
        output.writeMessage(1, reqList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < reqList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reqList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static OPRequestMulti parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OPRequestMulti parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OPRequestMulti parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OPRequestMulti parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OPRequestMulti parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OPRequestMulti parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static OPRequestMulti parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static OPRequestMulti parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static OPRequestMulti parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OPRequestMulti parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(OPRequestMulti prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sopr.common.OPRequestMulti}
     *
     * <pre>
     *批量请求结构-暂不支持
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OPRequestMultiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.internal_static_sopr_common_OPRequestMulti_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.internal_static_sopr_common_OPRequestMulti_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OPRequestMulti.class, Builder.class);
      }

      // Construct using sopr.common.Protocol.OPRequestMulti.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReqListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (reqListBuilder_ == null) {
          reqList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reqListBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.internal_static_sopr_common_OPRequestMulti_descriptor;
      }

      public OPRequestMulti getDefaultInstanceForType() {
        return OPRequestMulti.getDefaultInstance();
      }

      public OPRequestMulti build() {
        OPRequestMulti result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OPRequestMulti buildPartial() {
        OPRequestMulti result = new OPRequestMulti(this);
        int from_bitField0_ = bitField0_;
        if (reqListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            reqList_ = java.util.Collections.unmodifiableList(reqList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reqList_ = reqList_;
        } else {
          result.reqList_ = reqListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OPRequestMulti) {
          return mergeFrom((OPRequestMulti)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OPRequestMulti other) {
        if (other == OPRequestMulti.getDefaultInstance()) return this;
        if (reqListBuilder_ == null) {
          if (!other.reqList_.isEmpty()) {
            if (reqList_.isEmpty()) {
              reqList_ = other.reqList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReqListIsMutable();
              reqList_.addAll(other.reqList_);
            }
            onChanged();
          }
        } else {
          if (!other.reqList_.isEmpty()) {
            if (reqListBuilder_.isEmpty()) {
              reqListBuilder_.dispose();
              reqListBuilder_ = null;
              reqList_ = other.reqList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reqListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReqListFieldBuilder() : null;
            } else {
              reqListBuilder_.addAllMessages(other.reqList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getReqListCount(); i++) {
          if (!getReqList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OPRequestMulti parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OPRequestMulti) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .sopr.common.OPRequest reqList = 1;
      private java.util.List<OPRequest> reqList_ =
        java.util.Collections.emptyList();
      private void ensureReqListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reqList_ = new java.util.ArrayList<OPRequest>(reqList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          OPRequest, OPRequest.Builder, OPRequestOrBuilder> reqListBuilder_;

      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public java.util.List<OPRequest> getReqListList() {
        if (reqListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reqList_);
        } else {
          return reqListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public int getReqListCount() {
        if (reqListBuilder_ == null) {
          return reqList_.size();
        } else {
          return reqListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public OPRequest getReqList(int index) {
        if (reqListBuilder_ == null) {
          return reqList_.get(index);
        } else {
          return reqListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder setReqList(
          int index, OPRequest value) {
        if (reqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqListIsMutable();
          reqList_.set(index, value);
          onChanged();
        } else {
          reqListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder setReqList(
          int index, OPRequest.Builder builderForValue) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.set(index, builderForValue.build());
          onChanged();
        } else {
          reqListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder addReqList(OPRequest value) {
        if (reqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqListIsMutable();
          reqList_.add(value);
          onChanged();
        } else {
          reqListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder addReqList(
          int index, OPRequest value) {
        if (reqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqListIsMutable();
          reqList_.add(index, value);
          onChanged();
        } else {
          reqListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder addReqList(
          OPRequest.Builder builderForValue) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.add(builderForValue.build());
          onChanged();
        } else {
          reqListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder addReqList(
          int index, OPRequest.Builder builderForValue) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.add(index, builderForValue.build());
          onChanged();
        } else {
          reqListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder addAllReqList(
          Iterable<? extends OPRequest> values) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          super.addAll(values, reqList_);
          onChanged();
        } else {
          reqListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder clearReqList() {
        if (reqListBuilder_ == null) {
          reqList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reqListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public Builder removeReqList(int index) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.remove(index);
          onChanged();
        } else {
          reqListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public OPRequest.Builder getReqListBuilder(
          int index) {
        return getReqListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public OPRequestOrBuilder getReqListOrBuilder(
          int index) {
        if (reqListBuilder_ == null) {
          return reqList_.get(index);  } else {
          return reqListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public java.util.List<? extends OPRequestOrBuilder>
           getReqListOrBuilderList() {
        if (reqListBuilder_ != null) {
          return reqListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reqList_);
        }
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public OPRequest.Builder addReqListBuilder() {
        return getReqListFieldBuilder().addBuilder(
            OPRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public OPRequest.Builder addReqListBuilder(
          int index) {
        return getReqListFieldBuilder().addBuilder(
            index, OPRequest.getDefaultInstance());
      }
      /**
       * <code>repeated .sopr.common.OPRequest reqList = 1;</code>
       */
      public java.util.List<OPRequest.Builder>
           getReqListBuilderList() {
        return getReqListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          OPRequest, OPRequest.Builder, OPRequestOrBuilder>
          getReqListFieldBuilder() {
        if (reqListBuilder_ == null) {
          reqListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              OPRequest, OPRequest.Builder, OPRequestOrBuilder>(
                  reqList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          reqList_ = null;
        }
        return reqListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:sopr.common.OPRequestMulti)
    }

    static {
      defaultInstance = new OPRequestMulti(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sopr.common.OPRequestMulti)
  }

  public interface OPResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 errcode = 1;
    /**
     * <code>required int32 errcode = 1;</code>
     *
     * <pre>
     *状态，非0为失败
     * </pre>
     */
    boolean hasErrcode();
    /**
     * <code>required int32 errcode = 1;</code>
     *
     * <pre>
     *状态，非0为失败
     * </pre>
     */
    int getErrcode();

    // required bytes content = 2;
    /**
     * <code>required bytes content = 2;</code>
     *
     * <pre>
     *错误消息
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 2;</code>
     *
     * <pre>
     *错误消息
     * </pre>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code sopr.common.OPResponse}
   *
   * <pre>
   *响应结构
   * </pre>
   */
  public static final class OPResponse extends
      com.google.protobuf.GeneratedMessage
      implements OPResponseOrBuilder {
    // Use OPResponse.newBuilder() to construct.
    private OPResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OPResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OPResponse defaultInstance;
    public static OPResponse getDefaultInstance() {
      return defaultInstance;
    }

    public OPResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OPResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errcode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Protocol.internal_static_sopr_common_OPResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol.internal_static_sopr_common_OPResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OPResponse.class, Builder.class);
    }

    public static com.google.protobuf.Parser<OPResponse> PARSER =
        new com.google.protobuf.AbstractParser<OPResponse>() {
      public OPResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OPResponse(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<OPResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 errcode = 1;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errcode_;
    /**
     * <code>required int32 errcode = 1;</code>
     *
     * <pre>
     *状态，非0为失败
     * </pre>
     */
    public boolean hasErrcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 errcode = 1;</code>
     *
     * <pre>
     *状态，非0为失败
     * </pre>
     */
    public int getErrcode() {
      return errcode_;
    }

    // required bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 2;</code>
     *
     * <pre>
     *错误消息
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes content = 2;</code>
     *
     * <pre>
     *错误消息
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      errcode_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasErrcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static OPResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OPResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OPResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static OPResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static OPResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OPResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static OPResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static OPResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static OPResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static OPResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(OPResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sopr.common.OPResponse}
     *
     * <pre>
     *响应结构
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements OPResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Protocol.internal_static_sopr_common_OPResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Protocol.internal_static_sopr_common_OPResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OPResponse.class, Builder.class);
      }

      // Construct using sopr.common.Protocol.OPResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        errcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Protocol.internal_static_sopr_common_OPResponse_descriptor;
      }

      public OPResponse getDefaultInstanceForType() {
        return OPResponse.getDefaultInstance();
      }

      public OPResponse build() {
        OPResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OPResponse buildPartial() {
        OPResponse result = new OPResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errcode_ = errcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OPResponse) {
          return mergeFrom((OPResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OPResponse other) {
        if (other == OPResponse.getDefaultInstance()) return this;
        if (other.hasErrcode()) {
          setErrcode(other.getErrcode());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasErrcode()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OPResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OPResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 errcode = 1;
      private int errcode_ ;
      /**
       * <code>required int32 errcode = 1;</code>
       *
       * <pre>
       *状态，非0为失败
       * </pre>
       */
      public boolean hasErrcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 errcode = 1;</code>
       *
       * <pre>
       *状态，非0为失败
       * </pre>
       */
      public int getErrcode() {
        return errcode_;
      }
      /**
       * <code>required int32 errcode = 1;</code>
       *
       * <pre>
       *状态，非0为失败
       * </pre>
       */
      public Builder setErrcode(int value) {
        bitField0_ |= 0x00000001;
        errcode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 errcode = 1;</code>
       *
       * <pre>
       *状态，非0为失败
       * </pre>
       */
      public Builder clearErrcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errcode_ = 0;
        onChanged();
        return this;
      }

      // required bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 2;</code>
       *
       * <pre>
       *错误消息
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes content = 2;</code>
       *
       * <pre>
       *错误消息
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 2;</code>
       *
       * <pre>
       *错误消息
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 2;</code>
       *
       * <pre>
       *错误消息
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:sopr.common.OPResponse)
    }

    static {
      defaultInstance = new OPResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:sopr.common.OPResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sopr_common_OPRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sopr_common_OPRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sopr_common_OPRequestMulti_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sopr_common_OPRequestMulti_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sopr_common_OPResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sopr_common_OPResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016protocol.proto\022\013sopr.common\"\217\002\n\tOPRequ" +
      "est\022\016\n\006roleid\030\001 \002(\r\022\017\n\007channel\030\002 \002(\r\0224\n\007" +
      "charset\030\003 \002(\0162\036.sopr.common.OPRequest.Ch" +
      "arset:\003GBK\022\017\n\007keyword\030\004 \001(\014\022\023\n\010classid1\030" +
      "\005 \001(\004:\0010\022\023\n\010classid2\030\006 \001(\004:\0010\022\023\n\010classid" +
      "3\030\007 \001(\004:\0010\"=\n\007Channel\022\014\n\010MOBILEQQ\020\001\022\n\n\006W" +
      "ECHAT\020\002\022\007\n\003APP\020\004\022\007\n\003WEB\020\010\022\006\n\002H5\020\020\"\034\n\007Cha" +
      "rset\022\007\n\003GBK\020\001\022\010\n\004UTF8\020\002\"9\n\016OPRequestMult" +
      "i\022\'\n\007reqList\030\001 \003(\0132\026.sopr.common.OPReque" +
      "st\".\n\nOPResponse\022\017\n\007errcode\030\001 \002(\005\022\017\n\007con",
      "tent\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sopr_common_OPRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sopr_common_OPRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sopr_common_OPRequest_descriptor,
              new String[] { "Roleid", "Channel", "Charset", "Keyword", "Classid1", "Classid2", "Classid3", });
          internal_static_sopr_common_OPRequestMulti_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sopr_common_OPRequestMulti_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sopr_common_OPRequestMulti_descriptor,
              new String[] { "ReqList", });
          internal_static_sopr_common_OPResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_sopr_common_OPResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sopr_common_OPResponse_descriptor,
              new String[] { "Errcode", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
