// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sopr.proto

package sopr.common;

public final class Sopr {
  private Sopr() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OPRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint32 roleid = 1;
    boolean hasRoleid();
    int getRoleid();
    
    // required uint32 channel = 2;
    boolean hasChannel();
    int getChannel();
    
    // required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];
    boolean hasCharset();
    sopr.common.Sopr.OPRequest.Charset getCharset();
    
    // optional bytes keyword = 4;
    boolean hasKeyword();
    com.google.protobuf.ByteString getKeyword();
    
    // optional uint64 classid1 = 5 [default = 0];
    boolean hasClassid1();
    long getClassid1();
    
    // optional uint64 classid2 = 6 [default = 0];
    boolean hasClassid2();
    long getClassid2();
    
    // optional uint64 classid3 = 7 [default = 0];
    boolean hasClassid3();
    long getClassid3();
  }
  public static final class OPRequest extends
      com.google.protobuf.GeneratedMessage
      implements OPRequestOrBuilder {
    // Use OPRequest.newBuilder() to construct.
    private OPRequest(Builder builder) {
      super(builder);
    }
    private OPRequest(boolean noInit) {}
    
    private static final OPRequest defaultInstance;
    public static OPRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public OPRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sopr.common.Sopr.internal_static_sopr_common_OPRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sopr.common.Sopr.internal_static_sopr_common_OPRequest_fieldAccessorTable;
    }
    
    public enum Channel
        implements com.google.protobuf.ProtocolMessageEnum {
      MOBILEQQ(0, 1),
      WECHAT(1, 2),
      APP(2, 4),
      WEB(3, 8),
      H5(4, 16),
      ;
      
      public static final int MOBILEQQ_VALUE = 1;
      public static final int WECHAT_VALUE = 2;
      public static final int APP_VALUE = 4;
      public static final int WEB_VALUE = 8;
      public static final int H5_VALUE = 16;
      
      
      public final int getNumber() { return value; }
      
      public static Channel valueOf(int value) {
        switch (value) {
          case 1: return MOBILEQQ;
          case 2: return WECHAT;
          case 4: return APP;
          case 8: return WEB;
          case 16: return H5;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Channel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Channel>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Channel>() {
              public Channel findValueByNumber(int number) {
                return Channel.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sopr.common.Sopr.OPRequest.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Channel[] VALUES = {
        MOBILEQQ, WECHAT, APP, WEB, H5, 
      };
      
      public static Channel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Channel(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sopr.common.OPRequest.Channel)
    }
    
    public enum Charset
        implements com.google.protobuf.ProtocolMessageEnum {
      GBK(0, 1),
      UTF8(1, 2),
      ;
      
      public static final int GBK_VALUE = 1;
      public static final int UTF8_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Charset valueOf(int value) {
        switch (value) {
          case 1: return GBK;
          case 2: return UTF8;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Charset>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Charset>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Charset>() {
              public Charset findValueByNumber(int number) {
                return Charset.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return sopr.common.Sopr.OPRequest.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Charset[] VALUES = {
        GBK, UTF8, 
      };
      
      public static Charset valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Charset(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sopr.common.OPRequest.Charset)
    }
    
    private int bitField0_;
    // required uint32 roleid = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private int roleid_;
    public boolean hasRoleid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRoleid() {
      return roleid_;
    }
    
    // required uint32 channel = 2;
    public static final int CHANNEL_FIELD_NUMBER = 2;
    private int channel_;
    public boolean hasChannel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getChannel() {
      return channel_;
    }
    
    // required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];
    public static final int CHARSET_FIELD_NUMBER = 3;
    private sopr.common.Sopr.OPRequest.Charset charset_;
    public boolean hasCharset() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public sopr.common.Sopr.OPRequest.Charset getCharset() {
      return charset_;
    }
    
    // optional bytes keyword = 4;
    public static final int KEYWORD_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString keyword_;
    public boolean hasKeyword() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getKeyword() {
      return keyword_;
    }
    
    // optional uint64 classid1 = 5 [default = 0];
    public static final int CLASSID1_FIELD_NUMBER = 5;
    private long classid1_;
    public boolean hasClassid1() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getClassid1() {
      return classid1_;
    }
    
    // optional uint64 classid2 = 6 [default = 0];
    public static final int CLASSID2_FIELD_NUMBER = 6;
    private long classid2_;
    public boolean hasClassid2() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getClassid2() {
      return classid2_;
    }
    
    // optional uint64 classid3 = 7 [default = 0];
    public static final int CLASSID3_FIELD_NUMBER = 7;
    private long classid3_;
    public boolean hasClassid3() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public long getClassid3() {
      return classid3_;
    }
    
    private void initFields() {
      roleid_ = 0;
      channel_ = 0;
      charset_ = sopr.common.Sopr.OPRequest.Charset.GBK;
      keyword_ = com.google.protobuf.ByteString.EMPTY;
      classid1_ = 0L;
      classid2_ = 0L;
      classid3_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRoleid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChannel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCharset()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, roleid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, channel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, charset_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, keyword_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, classid1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, classid2_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, classid3_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, roleid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, channel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, charset_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, keyword_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, classid1_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, classid2_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, classid3_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sopr.common.Sopr.OPRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sopr.common.Sopr.OPRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sopr.common.Sopr.OPRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sopr.common.Sopr.OPRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sopr.common.Sopr.OPRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sopr.common.Sopr.OPRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sopr.common.Sopr.internal_static_sopr_common_OPRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sopr.common.Sopr.internal_static_sopr_common_OPRequest_fieldAccessorTable;
      }
      
      // Construct using sopr.common.Sopr.OPRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        roleid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        channel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        charset_ = sopr.common.Sopr.OPRequest.Charset.GBK;
        bitField0_ = (bitField0_ & ~0x00000004);
        keyword_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        classid1_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        classid2_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        classid3_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sopr.common.Sopr.OPRequest.getDescriptor();
      }
      
      public sopr.common.Sopr.OPRequest getDefaultInstanceForType() {
        return sopr.common.Sopr.OPRequest.getDefaultInstance();
      }
      
      public sopr.common.Sopr.OPRequest build() {
        sopr.common.Sopr.OPRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sopr.common.Sopr.OPRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sopr.common.Sopr.OPRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sopr.common.Sopr.OPRequest buildPartial() {
        sopr.common.Sopr.OPRequest result = new sopr.common.Sopr.OPRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roleid_ = roleid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.channel_ = channel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.charset_ = charset_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.keyword_ = keyword_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.classid1_ = classid1_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.classid2_ = classid2_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.classid3_ = classid3_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sopr.common.Sopr.OPRequest) {
          return mergeFrom((sopr.common.Sopr.OPRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sopr.common.Sopr.OPRequest other) {
        if (other == sopr.common.Sopr.OPRequest.getDefaultInstance()) return this;
        if (other.hasRoleid()) {
          setRoleid(other.getRoleid());
        }
        if (other.hasChannel()) {
          setChannel(other.getChannel());
        }
        if (other.hasCharset()) {
          setCharset(other.getCharset());
        }
        if (other.hasKeyword()) {
          setKeyword(other.getKeyword());
        }
        if (other.hasClassid1()) {
          setClassid1(other.getClassid1());
        }
        if (other.hasClassid2()) {
          setClassid2(other.getClassid2());
        }
        if (other.hasClassid3()) {
          setClassid3(other.getClassid3());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRoleid()) {
          
          return false;
        }
        if (!hasChannel()) {
          
          return false;
        }
        if (!hasCharset()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roleid_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              channel_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              sopr.common.Sopr.OPRequest.Charset value = sopr.common.Sopr.OPRequest.Charset.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                charset_ = value;
              }
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              keyword_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              classid1_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              classid2_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              classid3_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint32 roleid = 1;
      private int roleid_ ;
      public boolean hasRoleid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRoleid() {
        return roleid_;
      }
      public Builder setRoleid(int value) {
        bitField0_ |= 0x00000001;
        roleid_ = value;
        onChanged();
        return this;
      }
      public Builder clearRoleid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roleid_ = 0;
        onChanged();
        return this;
      }
      
      // required uint32 channel = 2;
      private int channel_ ;
      public boolean hasChannel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getChannel() {
        return channel_;
      }
      public Builder setChannel(int value) {
        bitField0_ |= 0x00000002;
        channel_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        channel_ = 0;
        onChanged();
        return this;
      }
      
      // required .sopr.common.OPRequest.Charset charset = 3 [default = GBK];
      private sopr.common.Sopr.OPRequest.Charset charset_ = sopr.common.Sopr.OPRequest.Charset.GBK;
      public boolean hasCharset() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public sopr.common.Sopr.OPRequest.Charset getCharset() {
        return charset_;
      }
      public Builder setCharset(sopr.common.Sopr.OPRequest.Charset value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        charset_ = value;
        onChanged();
        return this;
      }
      public Builder clearCharset() {
        bitField0_ = (bitField0_ & ~0x00000004);
        charset_ = sopr.common.Sopr.OPRequest.Charset.GBK;
        onChanged();
        return this;
      }
      
      // optional bytes keyword = 4;
      private com.google.protobuf.ByteString keyword_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasKeyword() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getKeyword() {
        return keyword_;
      }
      public Builder setKeyword(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        keyword_ = value;
        onChanged();
        return this;
      }
      public Builder clearKeyword() {
        bitField0_ = (bitField0_ & ~0x00000008);
        keyword_ = getDefaultInstance().getKeyword();
        onChanged();
        return this;
      }
      
      // optional uint64 classid1 = 5 [default = 0];
      private long classid1_ ;
      public boolean hasClassid1() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getClassid1() {
        return classid1_;
      }
      public Builder setClassid1(long value) {
        bitField0_ |= 0x00000010;
        classid1_ = value;
        onChanged();
        return this;
      }
      public Builder clearClassid1() {
        bitField0_ = (bitField0_ & ~0x00000010);
        classid1_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 classid2 = 6 [default = 0];
      private long classid2_ ;
      public boolean hasClassid2() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getClassid2() {
        return classid2_;
      }
      public Builder setClassid2(long value) {
        bitField0_ |= 0x00000020;
        classid2_ = value;
        onChanged();
        return this;
      }
      public Builder clearClassid2() {
        bitField0_ = (bitField0_ & ~0x00000020);
        classid2_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 classid3 = 7 [default = 0];
      private long classid3_ ;
      public boolean hasClassid3() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public long getClassid3() {
        return classid3_;
      }
      public Builder setClassid3(long value) {
        bitField0_ |= 0x00000040;
        classid3_ = value;
        onChanged();
        return this;
      }
      public Builder clearClassid3() {
        bitField0_ = (bitField0_ & ~0x00000040);
        classid3_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sopr.common.OPRequest)
    }
    
    static {
      defaultInstance = new OPRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sopr.common.OPRequest)
  }
  
  public interface OPRequestMultiOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .sopr.common.OPRequest reqList = 1;
    java.util.List<sopr.common.Sopr.OPRequest> 
        getReqListList();
    sopr.common.Sopr.OPRequest getReqList(int index);
    int getReqListCount();
    java.util.List<? extends sopr.common.Sopr.OPRequestOrBuilder> 
        getReqListOrBuilderList();
    sopr.common.Sopr.OPRequestOrBuilder getReqListOrBuilder(
        int index);
  }
  public static final class OPRequestMulti extends
      com.google.protobuf.GeneratedMessage
      implements OPRequestMultiOrBuilder {
    // Use OPRequestMulti.newBuilder() to construct.
    private OPRequestMulti(Builder builder) {
      super(builder);
    }
    private OPRequestMulti(boolean noInit) {}
    
    private static final OPRequestMulti defaultInstance;
    public static OPRequestMulti getDefaultInstance() {
      return defaultInstance;
    }
    
    public OPRequestMulti getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sopr.common.Sopr.internal_static_sopr_common_OPRequestMulti_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sopr.common.Sopr.internal_static_sopr_common_OPRequestMulti_fieldAccessorTable;
    }
    
    // repeated .sopr.common.OPRequest reqList = 1;
    public static final int REQLIST_FIELD_NUMBER = 1;
    private java.util.List<sopr.common.Sopr.OPRequest> reqList_;
    public java.util.List<sopr.common.Sopr.OPRequest> getReqListList() {
      return reqList_;
    }
    public java.util.List<? extends sopr.common.Sopr.OPRequestOrBuilder> 
        getReqListOrBuilderList() {
      return reqList_;
    }
    public int getReqListCount() {
      return reqList_.size();
    }
    public sopr.common.Sopr.OPRequest getReqList(int index) {
      return reqList_.get(index);
    }
    public sopr.common.Sopr.OPRequestOrBuilder getReqListOrBuilder(
        int index) {
      return reqList_.get(index);
    }
    
    private void initFields() {
      reqList_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getReqListCount(); i++) {
        if (!getReqList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < reqList_.size(); i++) {
        output.writeMessage(1, reqList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < reqList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, reqList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sopr.common.Sopr.OPRequestMulti parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sopr.common.Sopr.OPRequestMulti parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sopr.common.Sopr.OPRequestMulti parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sopr.common.Sopr.OPRequestMulti prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sopr.common.Sopr.OPRequestMultiOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sopr.common.Sopr.internal_static_sopr_common_OPRequestMulti_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sopr.common.Sopr.internal_static_sopr_common_OPRequestMulti_fieldAccessorTable;
      }
      
      // Construct using sopr.common.Sopr.OPRequestMulti.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getReqListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (reqListBuilder_ == null) {
          reqList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          reqListBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sopr.common.Sopr.OPRequestMulti.getDescriptor();
      }
      
      public sopr.common.Sopr.OPRequestMulti getDefaultInstanceForType() {
        return sopr.common.Sopr.OPRequestMulti.getDefaultInstance();
      }
      
      public sopr.common.Sopr.OPRequestMulti build() {
        sopr.common.Sopr.OPRequestMulti result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sopr.common.Sopr.OPRequestMulti buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sopr.common.Sopr.OPRequestMulti result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sopr.common.Sopr.OPRequestMulti buildPartial() {
        sopr.common.Sopr.OPRequestMulti result = new sopr.common.Sopr.OPRequestMulti(this);
        int from_bitField0_ = bitField0_;
        if (reqListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            reqList_ = java.util.Collections.unmodifiableList(reqList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.reqList_ = reqList_;
        } else {
          result.reqList_ = reqListBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sopr.common.Sopr.OPRequestMulti) {
          return mergeFrom((sopr.common.Sopr.OPRequestMulti)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sopr.common.Sopr.OPRequestMulti other) {
        if (other == sopr.common.Sopr.OPRequestMulti.getDefaultInstance()) return this;
        if (reqListBuilder_ == null) {
          if (!other.reqList_.isEmpty()) {
            if (reqList_.isEmpty()) {
              reqList_ = other.reqList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureReqListIsMutable();
              reqList_.addAll(other.reqList_);
            }
            onChanged();
          }
        } else {
          if (!other.reqList_.isEmpty()) {
            if (reqListBuilder_.isEmpty()) {
              reqListBuilder_.dispose();
              reqListBuilder_ = null;
              reqList_ = other.reqList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              reqListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getReqListFieldBuilder() : null;
            } else {
              reqListBuilder_.addAllMessages(other.reqList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getReqListCount(); i++) {
          if (!getReqList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              sopr.common.Sopr.OPRequest.Builder subBuilder = sopr.common.Sopr.OPRequest.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addReqList(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .sopr.common.OPRequest reqList = 1;
      private java.util.List<sopr.common.Sopr.OPRequest> reqList_ =
        java.util.Collections.emptyList();
      private void ensureReqListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          reqList_ = new java.util.ArrayList<sopr.common.Sopr.OPRequest>(reqList_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          sopr.common.Sopr.OPRequest, sopr.common.Sopr.OPRequest.Builder, sopr.common.Sopr.OPRequestOrBuilder> reqListBuilder_;
      
      public java.util.List<sopr.common.Sopr.OPRequest> getReqListList() {
        if (reqListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reqList_);
        } else {
          return reqListBuilder_.getMessageList();
        }
      }
      public int getReqListCount() {
        if (reqListBuilder_ == null) {
          return reqList_.size();
        } else {
          return reqListBuilder_.getCount();
        }
      }
      public sopr.common.Sopr.OPRequest getReqList(int index) {
        if (reqListBuilder_ == null) {
          return reqList_.get(index);
        } else {
          return reqListBuilder_.getMessage(index);
        }
      }
      public Builder setReqList(
          int index, sopr.common.Sopr.OPRequest value) {
        if (reqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqListIsMutable();
          reqList_.set(index, value);
          onChanged();
        } else {
          reqListBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setReqList(
          int index, sopr.common.Sopr.OPRequest.Builder builderForValue) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.set(index, builderForValue.build());
          onChanged();
        } else {
          reqListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addReqList(sopr.common.Sopr.OPRequest value) {
        if (reqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqListIsMutable();
          reqList_.add(value);
          onChanged();
        } else {
          reqListBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addReqList(
          int index, sopr.common.Sopr.OPRequest value) {
        if (reqListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReqListIsMutable();
          reqList_.add(index, value);
          onChanged();
        } else {
          reqListBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addReqList(
          sopr.common.Sopr.OPRequest.Builder builderForValue) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.add(builderForValue.build());
          onChanged();
        } else {
          reqListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addReqList(
          int index, sopr.common.Sopr.OPRequest.Builder builderForValue) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.add(index, builderForValue.build());
          onChanged();
        } else {
          reqListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllReqList(
          java.lang.Iterable<? extends sopr.common.Sopr.OPRequest> values) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          super.addAll(values, reqList_);
          onChanged();
        } else {
          reqListBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearReqList() {
        if (reqListBuilder_ == null) {
          reqList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          reqListBuilder_.clear();
        }
        return this;
      }
      public Builder removeReqList(int index) {
        if (reqListBuilder_ == null) {
          ensureReqListIsMutable();
          reqList_.remove(index);
          onChanged();
        } else {
          reqListBuilder_.remove(index);
        }
        return this;
      }
      public sopr.common.Sopr.OPRequest.Builder getReqListBuilder(
          int index) {
        return getReqListFieldBuilder().getBuilder(index);
      }
      public sopr.common.Sopr.OPRequestOrBuilder getReqListOrBuilder(
          int index) {
        if (reqListBuilder_ == null) {
          return reqList_.get(index);  } else {
          return reqListBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends sopr.common.Sopr.OPRequestOrBuilder> 
           getReqListOrBuilderList() {
        if (reqListBuilder_ != null) {
          return reqListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reqList_);
        }
      }
      public sopr.common.Sopr.OPRequest.Builder addReqListBuilder() {
        return getReqListFieldBuilder().addBuilder(
            sopr.common.Sopr.OPRequest.getDefaultInstance());
      }
      public sopr.common.Sopr.OPRequest.Builder addReqListBuilder(
          int index) {
        return getReqListFieldBuilder().addBuilder(
            index, sopr.common.Sopr.OPRequest.getDefaultInstance());
      }
      public java.util.List<sopr.common.Sopr.OPRequest.Builder> 
           getReqListBuilderList() {
        return getReqListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          sopr.common.Sopr.OPRequest, sopr.common.Sopr.OPRequest.Builder, sopr.common.Sopr.OPRequestOrBuilder> 
          getReqListFieldBuilder() {
        if (reqListBuilder_ == null) {
          reqListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              sopr.common.Sopr.OPRequest, sopr.common.Sopr.OPRequest.Builder, sopr.common.Sopr.OPRequestOrBuilder>(
                  reqList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          reqList_ = null;
        }
        return reqListBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:sopr.common.OPRequestMulti)
    }
    
    static {
      defaultInstance = new OPRequestMulti(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sopr.common.OPRequestMulti)
  }
  
  public interface OPResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 errcode = 1;
    boolean hasErrcode();
    int getErrcode();
    
    // required bytes content = 2;
    boolean hasContent();
    com.google.protobuf.ByteString getContent();
  }
  public static final class OPResponse extends
      com.google.protobuf.GeneratedMessage
      implements OPResponseOrBuilder {
    // Use OPResponse.newBuilder() to construct.
    private OPResponse(Builder builder) {
      super(builder);
    }
    private OPResponse(boolean noInit) {}
    
    private static final OPResponse defaultInstance;
    public static OPResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public OPResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sopr.common.Sopr.internal_static_sopr_common_OPResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sopr.common.Sopr.internal_static_sopr_common_OPResponse_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 errcode = 1;
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errcode_;
    public boolean hasErrcode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getErrcode() {
      return errcode_;
    }
    
    // required bytes content = 2;
    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString content_;
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }
    
    private void initFields() {
      errcode_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasErrcode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, errcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, content_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errcode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static sopr.common.Sopr.OPResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sopr.common.Sopr.OPResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static sopr.common.Sopr.OPResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static sopr.common.Sopr.OPResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(sopr.common.Sopr.OPResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements sopr.common.Sopr.OPResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sopr.common.Sopr.internal_static_sopr_common_OPResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sopr.common.Sopr.internal_static_sopr_common_OPResponse_fieldAccessorTable;
      }
      
      // Construct using sopr.common.Sopr.OPResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        errcode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sopr.common.Sopr.OPResponse.getDescriptor();
      }
      
      public sopr.common.Sopr.OPResponse getDefaultInstanceForType() {
        return sopr.common.Sopr.OPResponse.getDefaultInstance();
      }
      
      public sopr.common.Sopr.OPResponse build() {
        sopr.common.Sopr.OPResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private sopr.common.Sopr.OPResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        sopr.common.Sopr.OPResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public sopr.common.Sopr.OPResponse buildPartial() {
        sopr.common.Sopr.OPResponse result = new sopr.common.Sopr.OPResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.errcode_ = errcode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sopr.common.Sopr.OPResponse) {
          return mergeFrom((sopr.common.Sopr.OPResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(sopr.common.Sopr.OPResponse other) {
        if (other == sopr.common.Sopr.OPResponse.getDefaultInstance()) return this;
        if (other.hasErrcode()) {
          setErrcode(other.getErrcode());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasErrcode()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              errcode_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 errcode = 1;
      private int errcode_ ;
      public boolean hasErrcode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getErrcode() {
        return errcode_;
      }
      public Builder setErrcode(int value) {
        bitField0_ |= 0x00000001;
        errcode_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrcode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        errcode_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes content = 2;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sopr.common.OPResponse)
    }
    
    static {
      defaultInstance = new OPResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sopr.common.OPResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sopr_common_OPRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sopr_common_OPRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sopr_common_OPRequestMulti_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sopr_common_OPRequestMulti_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sopr_common_OPResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sopr_common_OPResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nsopr.proto\022\013sopr.common\"\217\002\n\tOPRequest\022" +
      "\016\n\006roleid\030\001 \002(\r\022\017\n\007channel\030\002 \002(\r\0224\n\007char" +
      "set\030\003 \002(\0162\036.sopr.common.OPRequest.Charse" +
      "t:\003GBK\022\017\n\007keyword\030\004 \001(\014\022\023\n\010classid1\030\005 \001(" +
      "\004:\0010\022\023\n\010classid2\030\006 \001(\004:\0010\022\023\n\010classid3\030\007 " +
      "\001(\004:\0010\"=\n\007Channel\022\014\n\010MOBILEQQ\020\001\022\n\n\006WECHA" +
      "T\020\002\022\007\n\003APP\020\004\022\007\n\003WEB\020\010\022\006\n\002H5\020\020\"\034\n\007Charset" +
      "\022\007\n\003GBK\020\001\022\010\n\004UTF8\020\002\"9\n\016OPRequestMulti\022\'\n" +
      "\007reqList\030\001 \003(\0132\026.sopr.common.OPRequest\"." +
      "\n\nOPResponse\022\017\n\007errcode\030\001 \002(\005\022\017\n\007content",
      "\030\002 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sopr_common_OPRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sopr_common_OPRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sopr_common_OPRequest_descriptor,
              new java.lang.String[] { "Roleid", "Channel", "Charset", "Keyword", "Classid1", "Classid2", "Classid3", },
              sopr.common.Sopr.OPRequest.class,
              sopr.common.Sopr.OPRequest.Builder.class);
          internal_static_sopr_common_OPRequestMulti_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sopr_common_OPRequestMulti_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sopr_common_OPRequestMulti_descriptor,
              new java.lang.String[] { "ReqList", },
              sopr.common.Sopr.OPRequestMulti.class,
              sopr.common.Sopr.OPRequestMulti.Builder.class);
          internal_static_sopr_common_OPResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_sopr_common_OPResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sopr_common_OPResponse_descriptor,
              new java.lang.String[] { "Errcode", "Content", },
              sopr.common.Sopr.OPResponse.class,
              sopr.common.Sopr.OPResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
